### ISSUE TITLE
handle sessions of other users

### ISSUE THREAD

**Issue by effyroth** [mpneuried/connect-redis-sessions#10]
req.session.getRedisSessionsModule()

Will return the internal instance of RedisSessions. You can use this to handle sessions of other users.

when a admin know a user's id is 10000,how to delete the user's session?

**Comment by mpneuried** [comment]
Yes you can do this.
Just have a look at the docs of redis-sessions https://github.com/smrchy/redis-sessions
I think you are searching for the method `.killsoid()'.
Let me know if this helps you.

**Comment by effyroth** [comment]
thanks,it works
