### ISSUE TITLE
Update tries to set `d` even when no `d` is supplied

### ISSUE THREAD

**Issue by smrchy** [mpneuried/connect-redis-sessions#8]
Resulting in 

```
{ [invalidValue: d must containt at least one key.]
  name: 'invalidValue',
  message: 'd must containt at least one key.' }
```

**Comment by AtlasDev** [comment]
any updates on this issue @mpneuried?

**Comment by mpneuried** [comment]
This is quite an old bug and i think it was fixed already ... but i'm not sure.
I cannot reproduce it.
If you having this Problem with the version `1.2.0` please let me know.
It would be helpful if you can provide me an example code that produces this or an similar error.

**Comment by colm-mcqs** [comment]
This is an issue in redis-sessions rather than connect-redis-sessions. See lines 593 -594 of https://github.com/smrchy/redis-sessions/blob/master/index.js

**Comment by mpneuried** [comment]
see #13
